/* ==============================================================================================================================
BCRYPT JS
npm i bcrypt

bcrypt is a password hashing library used to securely hash passwords before storing them in a database.

KEY METHODS:
    ASYNC (Recommended)
        1. bcrypt.hash(password, saltRounds)
        2. bcrypt.compare(password, hash)

    SYNC (For learning / testing only)
        1. bcrypt.hashSync(password, saltRounds)
        2. bcrypt.compareSync(password, hash)

SALT & SALT ROUNDS:
- Salt is a random value generated by bcrypt and mixed with the password before hashing.
- Salt rounds define how expensive (slow) the hashing process is.
- Higher salt rounds = more security but slower hashing.

FEATURES:
1. Converts passwords into unreadable hashed strings.
2. Allows secure comparison of plain text passwords with hashed passwords.

ADVANTAGES:
1. Real passwords are never stored in the database.
2. Even if the database leaks, passwords cannot be read.
3. Protects against brute-force attacks (trying many passwords until one works).
============================================================================================================================== */



const bcrypt = require("bcrypt");

let password = "sivananda123";

const hashedPassword = bcrypt.hashSync(password, 10);
console.log(hashedPassword);

const isPasswordTiGor = bcrypt.compareSync("tiGor", hashedPassword);
console.log("tiGor" + " is " + isPasswordTiGor);
const isPasswordSiva = bcrypt.compareSync("sivananda123", hashedPassword);
console.log("sivananda123" + " is " + isPasswordSiva);

/* OUTPUT
$2b$10$Y8sbGM9jo.6ATC4jQVSol.rjVj.T4A6.38MXBvwWBnS9u/SL5PEcu
tiGor is false
sivananda123 is true
*/



/* ==============================================================================================================================
NOTE:

1. The async methods (i.e., .hash & .compare) also accepts a callback funtion as an optional third argument.
2. In ".hash" method, the callback receives error, & hashed password as arguments.
3. In ".compare" method, the callback receives error, & boolean as arguments.
============================================================================================================================== */
